//
// Created by ma3 on 23.11.2016.
//

#ifndef MONTECARLOSIMULATION_DEEPFIRSTSEARCH_H
#define MONTECARLOSIMULATION_DEEPFIRSTSEARCH_H


class DeepFirstSearch {

};


#endif //MONTECARLOSIMULATION_DEEPFIRSTSEARCH_H
